# Theoritical Questions

In [1]:
import numpy as np 

In [128]:
# Example 1D array: 
arr = np.array([1, 2, 3, 4]) 
arr[::-1]

array([4, 3, 2, 1])

In [129]:
# Example 2D array: 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[::-1, :]  # Output: [[7, 8, 9], [4, 5, 6], [1, 2, 3]]
arr[:, ::-1]  # Output: [[3, 2, 1], [6, 5, 4], [9, 8, 7]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

# Practical Questions

In [29]:
np.random.seed(1)
arr =np.random.randint(1, 101, (3,3,))
print("Original Array:")
print(arr)

transpose_arr= arr.T
print('Transpose matrix is:')
print(transpose_arr)


Original Array:
[[38 13 73]
 [10 76  6]
 [80 65 17]]
Transpose matrix is:
[[38 10 80]
 [13 76 65]
 [73  6 17]]


In [16]:

array_1d = np.arange(10)

print("Original 1D Array:")
print(array_1d)


array_2x5 = array_1d.reshape(2, 5)
print("Reshaped to 2x5 Array:")
print(array_2x5)


array_5x2 = array_1d.reshape(5, 2)
print("Reshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]
Reshaped to 2x5 Array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [54]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Border of Zeros:")
print(array_6x6)


Original 4x4 Array:
[[0.4658077  0.72498012 0.30287132 0.48900729]
 [0.20367433 0.08861626 0.16568964 0.50299653]
 [0.78758101 0.90360187 0.21952409 0.73813097]
 [0.25780289 0.56420874 0.13242963 0.37208768]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.4658077  0.72498012 0.30287132 0.48900729 0.        ]
 [0.         0.20367433 0.08861626 0.16568964 0.50299653 0.        ]
 [0.         0.78758101 0.90360187 0.21952409 0.73813097 0.        ]
 [0.         0.25780289 0.56420874 0.13242963 0.37208768 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [58]:
array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [73]:
a= np.array(['python', 'numpy', 'pandas'])
uppercase = np.char.upper(a)
lowercase = np.char.lower(a)
titlecase = np.char.title(a)
capitalize = np.char.capitalize(a)

print("Original Array:")
print(a)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitle Case:") # Converts the first letter of each word in the string to uppercase and the rest to lowercase.
print(titlecase)

print("\nCapitalize:") # Capitalizes only the first letter of each string and converts the rest to lowercase.
print(capitalize)

Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


In [79]:
words = np.array(['hello', 'world', 'python'])
spaced_words = np.char.join(' ', words)
print("Original Array:",words)
print("Words with Spaces Between Characters:", spaced_words)

Original Array: ['hello' 'world' 'python']
Words with Spaces Between Characters: ['h e l l o' 'w o r l d' 'p y t h o n']


In [92]:
np.random.randint(6)

2

In [99]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[2,8,5],[2,9,4]])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Element-wise Addition:
[[ 3 10  8]
 [ 6 14 10]]

Element-wise Subtraction:
[[-1 -6 -2]
 [ 2 -4  2]]

Element-wise Multiplication:
[[ 2 16 15]
 [ 8 45 24]]

Element-wise Division:
[[0.5        0.25       0.6       ]
 [2.         0.55555556 1.5       ]]


In [108]:
import numpy as np


identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [119]:
np.random.seed(3)
from sympy import isprime

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if isprime(num)]

print("Random Integers:")
print(random_integers)

print("\nPrime Numbers:")
print(prime_numbers)


Random Integers:
[874 664 249 643 952 968 256 789 659 714 875 681 650 917 119 422 480 660
 940 605 423 398 504 538 337 474 662 834 258 959 316 641 947 858 581 872
 622 609 413 618 152 507 830 519 171 545 379 335 176 805  20 862 561 405
 383 718 500 540 887 566   0 704 274 372 959 677 184 952 967 165 765 686
 545 113   1 853 117 887 970 747 892 996 611 731 912 511 848 672 912 274
 843 183 864 223 141 421 414 560 957 289]

Prime Numbers:
[643, 659, 337, 641, 947, 379, 383, 887, 677, 967, 113, 853, 887, 223, 421]


In [125]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(low=10, high=35, size=30)  # Random temperatures between -10 and 35 degrees

# Reshape the array into weeks (4 full weeks of 7 days + 1 last week with 2 days)
weeks = daily_temperatures[:28].reshape(4, 7)  # First 28 days (4 weeks)
last_week = daily_temperatures[28:]            # Last 2 days

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)
last_week_average = np.mean(last_week)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages (First 4 Weeks):")
print(weekly_averages)

print("\nLast Week Average (2 days):")
print(last_week_average)


Daily Temperatures for the Month:
[20.50666237 13.14552601 34.82308884 20.83835727 25.4176322  34.47693136
 17.33386285 21.35779463 19.95342269 29.71472842 25.43635461 24.78815007
 13.11554376 10.77322987 15.80245973 10.31888727 16.86593671 33.54785902
 16.91919777 11.89470512 16.85880423 34.65065877 20.56561055 28.25398847
 25.37973639 14.51850825 28.59573524 19.13704179 29.4190508  29.83306692]

Weekly Averages (First 4 Weeks):
[23.79172298 20.73417487 17.45826426 24.44303992]

Last Week Average (2 days):
29.626058858067825
